version: "3.9"
services:
  gogo:
    build: .
    environment:
      HEY: hey
    ports:
      - 4271:4271

  mongo:
    image: mongo
    restart: always
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "mongo_db"
