version: "3.9"
services:

  gogo:
    build: .
    ports:
      - 4271:4271

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://0.0.0.0:4271"
        tag: "mongo"

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:4271"
        tag: "mongo"
